version: '3'
services:

  #PHP Service
  bread_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: bread_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: bread_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bread_app-network

  #Nginx Service
  bread_webserver:
    image: nginx:alpine
    container_name: bread_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bread_app-network

  #MySQL Service
  bread_db:
    image: mysql:5.7.22
    container_name: bread_db
    restart: unless-stopped
    tty: true
    ports:
      - "33064:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - bread_app-network

#Docker Networks
networks:
  bread_app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
